name: Convert JSON to CSV

on:
  push:
    paths:
      - 'ratings.json'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Convert JSON to CSV
      run: |
        python convert.py

    - name: Commit and push CSV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ratings.csv
        git commit -m "Auto-generate ratings.csv from ratings.json"
        git push
